version: "3.9"

services:
  db:
    image: postgres:15
    container_name: agri_postgres
    restart: always
    environment:
      POSTGRES_USER: agri_user
      POSTGRES_PASSWORD: agri_pass
      POSTGRES_DB: agri_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: agri_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./ai-model:/app/ai-model

volumes:
  pgdata:
